### ISSUE TITLE
Performance Optimisation - Lazy Loading - Image Poster/Thumbail while video is still loading

### ISSUE THREAD

**Issue by lucashfreitas** [vimeo/player.js#613] opened 2020-08-19 05:16 UTC
I have a page with 3 vimeo iframe videos autoplaying in background. I would like to know if that's possible to add a fallback image, like a `poster` attribute on `<video>` component.

Sometimes the video has an empty screen while it's loading. It's possible to add a poster image inside the video component that is rendered by vimeo? 

I am initialing the Iframe using the player id and the options API, but I didn't see any option to add the lazy loading attribute, is that possible to be done without using a custom `<iframe>` component?

I have also noticed that vimeo sends a lot of HTTP requests, like 14 per second on the address: `https://fresnel.vimeocdn.com/add/player-stats?beacon=1&session-id=5676dad4324c61c334948489b54e`

Here is a evidence from the high cpu usage from vimeo Iframe. Only the vimeo frame uses around 10-15% of the CPU, is that normal, considering that I am using a 16gb i7 macbook pro?

![image](https://user-images.githubusercontent.com/11416392/90617473-d36c8b80-e262-11ea-919f-190b72f59e88.png)

Does anyone faced the same problem or have any tips to share? 

Thanks

**Comment by luwes** [comment] 2020-08-20 14:42
@lucashfreitas thanks for the feedback. in regard to the memory and CPU that's normal, if you compare it with other video platforms it will be in the same range.

---

we don't have a built in solution for lazy loading but this is something that can be done with an extra library. there are a few available https://www.google.com/search?q=iframe+lazy+load+github

just be sure to setup the Player API when the loading of the iframe is complete, I believe the `onload` event should do the trick.

another option is something like https://github.com/luwes/lite-vimeo-embed

---

note that getting the thumbnail of a Vimeo video has to go through a Vimeo backend API. 
the oEmbed API is probably the easiest, https://developer.vimeo.com/api/oembed/videos

---

hope this helps a bit. closing the issue as it's not a bug.

**Closed by luwes** 2020-08-20 14:42 UTC
