### ISSUE TITLE
SyntaxError: Unexpected identifier "blockerIframeLoaded"

### ISSUE THREAD

**Issue by joker-777** [vimeo/player.js#397] opened 2019-02-28 19:07 UTC
Hi, we are seeing in our js error tracking quite a few errors like this

`SyntaxError: Unexpected identifier "blockerIframeLoaded"``

This happens here

File "node_modules/@vimeo/player/dist/player.es.js" line 924 col 1 in w
data = JSON.parse(data);

File "node_modules/@vimeo/player/dist/player.es.js" line 1080 col 1 in u
var data = parseMessageData(event.data);

Basically when JSON parsing the event data. Any ideas what this could be?

We use the vimeo npm package `@vimeo/player` with the version 2.6.7

<img width="1208" alt="screen shot 2019-02-06 at 23 57 47" src="https://user-images.githubusercontent.com/378859/53591511-2ed42680-3b62-11e9-966e-5e4201cfff87.png">

**Comment by luwes** [comment] 2019-02-28 19:20
@joker-777 I think this is caused by some source sending messages via postMessage in your website window object which the player api tries to parse as json.

It could be even browser extensions.

Do you have an idea what could be sending messages?

**Comment by joker-777** [comment] 2019-02-28 19:24
Unfortunately, I don't know. It happens to users we don't know personally. I wish the vimeo js library would be more careful with the way they accept these postMessages.

**Comment by luwes** [comment] 2019-02-28 21:04
@joker-777 we do only accept messages from the Vimeo domain. see line
https://github.com/vimeo/player.js/blob/30427a1c79a19e5724fc4dd1b14b8e2e0c81ed4b/src/player.js#L69-L69

must be a real edge case that it gets to that code.

**Comment by joker-777** [comment] 2019-03-01 14:41
Ah, I see. I guess it is some kind of iframe blocker but it is hard to verify. So far it only has happened on macs with Safari 12.

**Comment by luwes** [comment] 2019-03-07 18:50
Closed by #399

**Closed by luwes** 2019-03-07 18:50 UTC

**Comment by joker-777** [comment] 2019-03-08 21:25
Amazing, thanks!
