### ISSUE TITLE
Triggering playback through api fails

### ISSUE THREAD

**Issue by andrewohlmann** [vimeo/player.js#243] opened 2018-05-08 04:22 UTC
I came across this one in the course of updating code to comply with Chrome's media engagement behavior. The context is a user-customizable player that allows one to set an autoplaying video inside their page.

### Expected Behavior

In line with the guidelines put forth by apple for auto-playing video, I am trying to autoplay initially and then expose a play button to the viewer if auto-play fails.

### Actual Behavior

The play() promise returns a positive result, and the player un-pauses but fails to progress or load the video. One has to pause the video manually and then restart playback using the embed's play button in order for it to work.

It's my understanding that Firefox has not yet implemented any media playback rules like the ones that Safari and Chrome have, so autoplay is successful within firefox.

### Steps to Reproduce

I've included a jsfiddle here
https://jsfiddle.net/ke9L7ey4/2/

**Comment by jybleau** [comment] 2018-05-09 19:29
A temporary workaround to this "bug" could be to test `getPaused()` and to include the `autoplay` option. Tested with FF, Safari and Chrome 66.

Like this:

```
var options = {
  id: 59777392,
  autoplay: true
};
```

```
player.ready().then(function() {
  player.getPaused().then(function(paused) {
    if (paused) {
      showPlayButton();
    }
  });
});
```

**Comment by jybleau** [comment] 2018-05-09 21:53
Ok, then one last thought  ...maybe you can load the video when its container enters the viewport using:
[$.onScreen](https://silvestreh.github.io/onScreen/) 
or
[http://qnimate.com/how-to-detect-element-entered-viewport/](http://qnimate.com/how-to-detect-element-entered-viewport/)

**Comment by danrossi** [comment] 2018-05-12 17:14
I mentioned in other tickets. A mute / setting volume to 0 then play command should begin playback like the others. This doesn't. It just sits there

```
this.vimeoPlayer.getPaused().then((paused) => {
                if (paused) {
                  
                    this.vimeoPlayer.setVolume(0);
                    this.vimeoPlayer.play();

                }
            });
```

**Comment by luwes** [comment] 2018-05-15 01:09
Duplicate of #242

**Closed by luwes** 2018-05-15 01:09 UTC
Labels: bug
