### ISSUE TITLE
Allow "playsinline" video attribute to be passed as embed option

### ISSUE THREAD

**Issue by klase** [vimeo/player.js#86] opened 2016-11-25 13:26 UTC
Now that webkit has eased it's video restrictions (https://webkit.org/blog/6784/new-video-policies-for-ios/) and the "playsinline" attribute is part of the HTML spec (https://github.com/whatwg/html/pull/1444), wouldn't it make sense to add "playsinline" as an embed option?

**Comment by bdougherty** [comment] 2016-11-26 16:31
Duplicate of #76

**Closed by bdougherty** 2016-11-26 16:31 UTC
