### ISSUE TITLE
Some private videos are embeddable using iframe but not using Javascript API

### ISSUE THREAD

**Issue by pepawel** [vimeo/player.js#274] opened 2018-06-19 19:45 UTC
### Expected Behavior
Video which can be embedded using iframe should be also embeddable using Javascript API.

### Actual Behavior
Some private videos are embeddable using iframe but not using Javascript API.

### Steps to Reproduce
See the bug demonstration at:
https://jsfiddle.net/q3nL5hsb/

Here is a code used in demo:
```
<p>Private video - JS API:</p>
<div id="a"></div>
<p>Private video - iframe:</p>
<iframe src="//player.vimeo.com/video/249502052"></iframe>
<p>Public video - JS API:</p>
<div id="b"></div>
<script src="https://player.vimeo.com/api/player.js"></script>
<script>
new Vimeo.Player('a', {id: 249502052});
new Vimeo.Player('b', {id: 131766159});
</script>
```

**Comment by luwes** [comment] 2018-06-27 12:57
Is this still an issue? I can see 3 video players in the fiddle.

**Comment by pepawel** [comment] 2018-06-27 22:20
@luwes you are right, but this is beacuse video owner of video with id 249502052 probably relaxed settings of this video.

**Comment by tenacex** [comment] 2018-07-18 19:02
Hi everyone, we are aware of an issue embedding videos on a subdomain of an enabled domain. For example, if a user embedded a video on yyy.xxx.com and xxx.com is an allowed domain, we would expect the video to load succesfully. However this is not working because of an issue with the api. They are currently working on the fix for that, and I will be tracking the issue in the ticket here: https://github.com/vimeo/player.js/issues/270

I am going to close this as I believe this issue is the same. However, if it is not, feel free to open it back, just be sure to provide the video ID's so that I can confirm that this is not a duplicate issue.

**Closed by tenacex** 2018-07-18 19:02 UTC
Labels: bug
