### ISSUE TITLE
?playsinline=0 does not work on Android if play is initiated via Javascript

### ISSUE THREAD

**Issue by travisrobie** [vimeo/player.js#570] opened 2020-05-04 16:20 UTC
### Expected Behavior
Initiate playback of Vimeo video via javascript on Android device. 
Video should open fullscreen in the native player.

### Actual Behavior
Throws an error. Video stays inline.
`player.js:10 Failed to execute 'requestFullscreen' on 'Element': API can only be initiated by a user gesture.`

### Steps to Reproduce
Append `?playsinline=0` to video url for iframe src.
Play video via javascript in browser on android device.

See [http://travisrobie.me/vimeo_programmatic_play.html](http://travisrobie.me/vimeo_programmatic_play.html)

**Comment by luwes** [comment] 2020-07-29 17:13
Duplicate of #219

**Closed by luwes** 2020-07-29 17:13 UTC
Labels: bug
