### ISSUE TITLE
Any possibility of qualities api 

### ISSUE THREAD

**Issue by danrossi** [vimeo/player.js#552] opened 2020-04-02 15:48 UTC
For years there hasn't been an api for bitrate list and control with custom controlbars with pro accounts. 

Is there ever going to be the possibility of bitrate control with a custom menu like the Chrome player controls has ?

**Comment by luwes** [comment] 2020-07-29 17:15
Duplicate of #601

**Closed by luwes** 2020-07-29 17:15 UTC
Labels: enhancement
