### ISSUE TITLE
Private video prevents reusing of Vimeo.player, page basically crashes

### ISSUE THREAD

**Issue by Larzans** [vimeo/player.js#132] opened 2017-03-30 15:21 UTC
### Expected Behavior
An existing Vimeo.player element can be used to load a new video even if the previous one couldn't be reproduced because it was set to private.
### Actual Behavior
As soon as a private video has been loaded into the player it becomes useless and either always shows the player with the privacy message (Case A), or it crashes (console: Uncaught TypeError: Cannot read property 'sentry' of undefined....) and only a black window shows up instead of a new video when trying to load another one (Case B)
### Steps to Reproduce
The full page can be seen here: http://aproductions360.com/en/service/long-format/
Simplified JSFIDDLE: https://jsfiddle.net/Larzan/qonqt7hw/10/
Case A: load the page and click on the first thumbnail FIRST, then try another video
Case B: load the page, open any video but the first, then try the first one and afterwards another video

**Comment by astashkevich** [comment] 2017-05-31 06:55
+1

**Comment by luwes** [comment] 2018-03-02 19:22
Duplicate of #166

**Closed by luwes** 2018-03-02 19:22 UTC
Labels: bug
