### ISSUE TITLE
Vimeo video on fullscreen does not detect 'ended' event

### ISSUE THREAD

**Issue by nestordsanchezr** [vimeo/player.js#70] opened 2016-10-25 20:26 UTC
### Expected Behavior

When a video goes fullscreen, and on 'ended' event I load another video (With loadVideo), next video should play, even if I'm on fullscreen.
### Actual Behavior

When a video goes fullscreen, and on 'ended' event I want to reproduce another video (with loadVideo), next video doesn't reproduce. The problem (as I see) is that on fullscreen, 'ended' event is not detected.
### Steps to Reproduce

https://player.vimeo.com/playground
1. Play video.
2. Go almost at the end of video.
3.1 On "no full screen", you get the "finish" event.
![screen shot 2016-10-25 at 1 54 57 pm](https://cloud.githubusercontent.com/assets/1417025/19699906/bee08246-9aba-11e6-8bd8-18843f278494.png)

3.2 On "full screen, you don't get "finish" event.
![screen shot 2016-10-25 at 1 55 31 pm](https://cloud.githubusercontent.com/assets/1417025/19699934/d525efc8-9aba-11e6-8521-1c07fb2b199c.png)
#### Tech details:
1. Chrome Version 54.0.2840.71 (64-bit)
2. Using api player on https://player.vimeo.com/api/player.js
3. According to documentation: https://github.com/vimeo/player.js
4. Removed ?api=1 ; This is how I load video: 

``` ruby
%iframe#player1{allowfullscreen: "", frameborder: "0", height: "354", mozallowfullscreen: "", src: "#{video_url}?&player_id=player1&autoplay=1", webkitallowfullscreen: "", width: "630"}
```
### Update

Once fullscreen has been turned on, API does not detect 'ended', despite "fullscreen" is turned off.
![screen shot 2016-10-25 at 5 01 04 pm](https://cloud.githubusercontent.com/assets/1417025/19705944/e9d7a5e6-9ad4-11e6-9a67-a29637f451f0.png)

**Comment by bdougherty** [comment] 2016-10-27 15:42
The playground page is using our previous API library. I'm unable to replicate on the demo page that uses this library: https://player.vimeo.com/api/demo.

Judging from the screenshots, my guess is that you're running into #34.

**Comment by bdougherty** [comment] 2016-12-06 20:49
Going to close this because I’m pretty sure it’s a duplicate of #34. If you still see the issue after we resolve #34, please comment and I’ll reopen this one.

**Closed by bdougherty** 2016-12-06 20:49 UTC
