### ISSUE TITLE
Issue with Fancybox

### ISSUE THREAD

**Issue by Soullighter** [vimeo/player.js#329] opened 2018-10-15 12:52 UTC
This issue is reference of #130 issue.
@thomasbrodin didn't see the same error when he close modal box, same message appear in console. Also when you want to open another time same modal box, you can't auto play video for second time.
I have same problem that is why i open same issue.
Any conclusions on this one?

**Comment by luwes** [comment] 2018-10-19 03:06
Can't it be resolved with the suggestion here?
https://github.com/vimeo/player.js/issues/130#issuecomment-287917290

**Comment by Soullighter** [comment] 2018-10-19 04:43
🤔 It's a same reference that i link. I think i make my self clear in comment above?

**Comment by luwes** [comment] 2019-01-09 19:48
Duplicate of #130

**Closed by luwes** 2019-01-09 19:48 UTC
Labels: help wanted
