### ISSUE TITLE
load video and player options

### ISSUE THREAD

**Issue by thatvideowebguy** [vimeo/player.js#93] opened 2016-12-07 15:17 UTC
Hi, 

I'm loading inside a player with options a new vimeo id.
The video is loaded and playable  inside player but the options  (portrait, title, ..) are not used.

here's the code used to create the player (on ready)

```

  var iframe = $('#vimeoContainer');
    var options = {
		id : 191611447,
        portrait: 0,
		title : 0,
		byline: 0,
    };

    var player = new Vimeo.Player(iframe, options);
```

and here's the code to load a video insite this player
```

player.loadVideo(sl).then(function(id) {
    // the video successfully loaded
}).catch(function(error) {
    switch (error.name) {
        case 'TypeError':
            // the id was not a number
            break;

        case 'PasswordError':
            // the video is password-protected and the viewer needs to enter the
            // password first
            break;

        case 'PrivacyError':
            // the video is password-protected or private
            break;

        default:
            // some other error occurred
            break;
    }
});
```

Thanks for your help and time

### Expected Behavior
Video loaded with same options for the player (no title, ...) as before
### Actual Behavior
The video is loaded and playable  inside player but the options  (portrait, title, ..) are not used.

**Comment by bdougherty** [comment] 2016-12-07 16:46
This is a duplicate of #71

**Closed by bdougherty** 2016-12-07 16:46 UTC
