### ISSUE TITLE
Cannot Embed with only 'id' using javascript API

### ISSUE THREAD

**Issue by sblanchon** [vimeo/player.js#294] opened 2018-07-27 09:54 UTC
### Expected Behavior
I wanted a player embedded in a div containing few 'data-vimeo-*' attributes, and a 'data-options' to pass options to be tested before being passed to iframe embedded
options are {id: 999999, background: true, autoplay: true, loop: true} in JSON stringified format.

**_my backend code_**
`<div id="vimeo-player-id-${uuid}"
        class="${'js-video-player vimeo-player-iframe ' + (pdict.iframeclassname ? pdict.iframeclassname : '')}"
        data-vimeo-title="0"
        data-vimeo-playsinline="1"
        data-options="${JSON.stringify(optionsToEmbed)}"
    ></div>`

In javascript, i passed to Vimeo.Player() constructor, the DOM element with class 'js-video-player' and an option object, with correct id, background, autoplay and loop properties, got with jQuery.data() method.

I expected my vimeo player to load the video corresponding to my 'id', but i got a 404 NOTFOUND error thrown by API ?

### Actual Behavior
Seems there is a javascript error when encoding 'e' which is my video url calculated with my options ?
`var i = "https://vimeo.com/api/oembed.json?url=" + encodeURIComponent(e);`
The url of my encoded video seems to contains en extra " (double-quote character) at the end of it, that make server respond a 404

### Steps to Reproduce

`$('.js-video-player').each(function () {
    var options = $(this).data('options') || {};
    if (options.id) {
                    options.muted = options.autoplay; // To allow autoplay we need to mute the video
                    options.responsive = 1;
                    //options.url = 'https://player.vimeo.com/video/' + parseInt(options.id, 10);
                    var player = new Vimeo.Player(this, options);
    }
});`

Note: if i uncomment the calculation of options.url to pass in to the constructor, it works !

My questions :
1) Is there a reason why i can't only pass in my 'id' for the player to work ? Is it a bug ?
2) data-vimeo-muted=1 attribute was not propagated to <iframe> while embedding, so i had to pass it as an option in javascript ? Is it the proper way ? Is there data-vimeo-* attributes that are not taken into account when embedding ??

Thanks a lot for you responses.
Stéphane

**Comment by tenacex** [comment] 2018-08-06 15:30
Hi @sblanchon Thank you for the extremely descriptive post. Could you please include a jsfiddle to ensure that I am reproducing your issue accurately before I look into this? Thanks.

**Comment by danielstgt** [comment] 2018-09-21 17:00
This issue is the same as https://github.com/vimeo/player.js/issues/270

**Comment by luwes** [comment] 2018-10-19 03:12
Duplicate of #270

**Closed by luwes** 2018-10-19 03:12 UTC
