### ISSUE TITLE
setCurrentTime fails silently for Vimeo iframe embeds in iOS Safari

### ISSUE THREAD

**Issue by ehmorris** [vimeo/player.js#117] opened 2017-02-08 00:16 UTC
### Expected Behavior

For `setCurrentTime` to seek the Vimeo player and display the frame at the passed timestamp. Or for `setCurrentTime` to return an error in the `catch` method.

For comparison, the YouTube iframe player will display the frame at the passed timestamp in iOS Safari when `seekTo` is called via the iframe API.

### Actual Behavior

The player does not seek and does not return an error in iOS Safari.

### Steps to Reproduce

[CodePen debug view](http://s.codepen.io/ehmorris/debug/BpOQOy/jVApojeqBgRr) | [CodePen editor view](https://codepen.io/ehmorris/pen/BpOQOy)

##### Correct behavior on desktop
1. Open the linked debug view on a desktop browser.
2. Scroll up/down.
3. Note the video scrubbing in the background, also note the console logging `setCurrentTime` invocation, and success or failure. 

##### Incorrect behavior on mobile
1. Open the linked debug view in iOS Safari.
2. Scroll up/down.
3. Note the video not responding, also note the console logging `setCurrentTime` invocation but never logging success or failure.

### Compare to YouTube

[CodePen debug view](http://s.codepen.io/ehmorris/debug/bgxByp/nqkwvKVRZGaA) | [CodePen editor view](http://codepen.io/ehmorris/pen/bgxByp)

##### Correct behavior on mobile
1. Open the linked debug view in iOS Safari.
2. Scroll up/down.
3. Note the video scrubbing successfully.

### Additional Note

I think this may be resolved by enabling the new [playsinline](https://webkit.org/blog/6784/new-video-policies-for-ios) feature within the iframe embed.

**Comment by ehmorris** [comment] 2017-02-15 16:14
@bdougherty do you think I can expect this behavior to be added to the vimeo player on mobile?

**Comment by bdougherty** [comment] 2017-02-15 18:39
@ehmorris can you try adding a listener for the `error` event? There is a bug right now that prevents the method-specific error response messages from going out if you aren't listening for `error` events. I hope to have a fix for that soon.

We don't have any plans at the moment to add support for inline playback on iOS.

**Comment by ksolberg** [comment] 2017-03-16 16:59
Are there any workarounds for this?

**Comment by enoziak** [comment] 2017-10-31 18:47
Did this ever get worked out? I'm running into the same issue.

**Comment by ehmorris** [comment] 2017-10-31 19:15
Afaik there are no workarounds for my use-case.

Also worth noting that since I posted this, YouTube/iOS behavior has changed such that the mobile player autoplays the video from the scrubbed timestamp.

**Comment by luwes** [comment] 2018-02-22 23:02
#210 will add a `playsinline` parameter

**Comment by luwes** [comment] 2018-03-02 15:21
@ehmorris would you mind having a look if this issue persists? We recently had several fixes go out, including the throwing errors correctly in `catch`.

**Comment by ehmorris** [comment] 2018-03-02 16:19
@luwes thanks for coming back to this. I went through my reproduction steps and noticed that before I initiate playback, I get the error `Error: The viewer must initiate playback first.`, and after I initiate playback it seeks to the time and continues to play.

**Comment by luwes** [comment] 2018-03-02 19:23
Duplicate of #166

**Comment by luwes** [comment] 2018-03-02 19:29
(^^ scusi, was in the wrong window)

I think currently that is the best we can do. `setCurrentTime()` internally calls `play()` which will fail because it's done without user interaction. Only for muted videos this can be done I believe.

Would you like to see different behaviour in this case?

**Comment by ehmorris** [comment] 2018-03-02 19:35
@luwes sorry, to clarify I think my issue is resolved.

It would be awesome if I could set the time on a muted, uninitialized video though.

**Comment by luwes** [comment] 2018-03-02 19:40
Awesome! I will reference #20 here to keep that in mind when adding a start time option.
Thanks for your feedback!

**Closed by luwes** 2018-03-02 19:40 UTC
Labels: bug
