### ISSUE TITLE
Edge: play() causes "play" event but video doesn't play

### ISSUE THREAD

**Issue by pedantic-git** [vimeo/player.js#453] opened 2019-07-03 10:53 UTC
### Expected Behavior

I've got a &lt;vue-vimeo-player&gt; (which is a thin wrapper around this SDK) in my app. There's a "play" button that sends the `play()` event to the video. Video is a private video, although I think the issue also happens with public ones.

Expected behaviour (and actual behaviour in browsers other than Edge) is that the video starts playing and then the "play" event is fired.

### Actual Behavior

In Edge, the "play" event is fired but the video doesn't start playing. With `{controls: false}` there is no visual feedback of this. If I set `{controls: true}` the video goes dark and has a loading spinner forever.

### Steps to Reproduce

1. Check out this repo: https://github.com/fishpercolator/edge-vimeo
2. `yarn && yarn dev`
3. Visit http://localhost:3000/ in Edge browser.
4. Click the "Play" button.

All the relevant code is here on [this page](https://github.com/fishpercolator/edge-vimeo/blob/master/pages/index.vue). Afaict from the vue-vimeo-player sources, the Vue methods and events are just proxies to the player.js methods and events with no additional Vue magick on top.

Thanks for your help!

**Comment by luwes** [comment] 2019-07-11 14:58
Thanks for the feedback @pedantic-git, would you mind verifying it is the same behavior with public videos? And any chance you just have plain Vanilla JS example?

**Comment by pedantic-git** [comment] 2019-07-11 15:48
Hi @luwes - I will try putting a native example together with a public video.

**Comment by pedantic-git** [comment] 2019-07-11 16:32
Hi @luwes - I can't reproduce it with the public video 148751763 but I can with a private Video using only vanilla JavaScript and the Player SDK:

https://github.com/fishpercolator/edge-vimeo/blob/master/static/test.html has an example that has the issue, even if the two lines attaching events to the player are commented out.

You will need to have hostname=localhost to see the video - you can still run "yarn" in that top-level dir and then visit http://localhost:3000/test.html to view it on a local web server.

I hope that helps!!

**Comment by luwes** [comment] 2020-07-29 18:56
I think this might be caused by the async nature of Vue rendering where if you would set an attribute/property but it's actually called on the next frame because of the VDOM. this in turn makes the browser think it's not a user gesture and rejects the play promise...

closing as this is something that would better be discussed on Stackoverflow.

**Closed by luwes** 2020-07-29 18:56 UTC
Labels: help wanted

**Comment by pedantic-git** [comment] 2020-07-30 10:19
Hi @luwes - as mentioned in my comment above, I can reproduce the issue with vanilla JS. Vue events don't work the way you've described (they're different from the setting of properties).

However, I appreciate that while I'm still confident this is a bug, non-Chromium Edge is now not a priority for anyone.
