### ISSUE TITLE
Getting video to play without autoplay on

### ISSUE THREAD

**Issue by gidmeister2** [vimeo/player.js#291] opened 2018-07-15 19:24 UTC
### How to reproduce: embed a Vimeo video into a page, and use the normal JavaScript instructions as provided in your API to create a 'ready' event.   In that event, call the API  'play' function.   

The code is so simple that I have not supplied a sample.  If you really need a sample, I'll learn to use codepen.io and provide it.

**Comment by tenacex** [comment] 2018-07-18 19:04
Hi @gidmeister2 could you please provide what environment you are doing this in ie browser, browser version, and os. I assume this is due to autoplay restrictions, as you cannot play a video without a user interaction in many recent browsers.

**Comment by gidmeister2** [comment] 2018-07-18 20:08
Dear Dylan Dove,

It is in both:
EDGE
And
Chrome
My laptop uses windows 10, and I generally keep my browsers up to date.
It probably is due to autoplay restrictions, but if that is true, could I put a timer in the  ready event that starts the video a second later?
Thanks,
Gideon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tenacex** [comment] 2018-07-18 20:30
Could you please check if changing your autoplay settings solves the issue? 
In edge: Edge -> Advanced Settings -> Allow sites to automatically play media.

Chrome has started blocking autoplaying videos. There is no programatic way around this, otherwise everyone would be doing it! The video needs to play directly from a user interaction with the video element.

Please let me know if changing your edge settings solves the issue. If so, it is an autoplay issue and unfortunately there is nothing we can do to fix it!

**Comment by gidmeister2** [comment] 2018-07-19 20:32
OK, I tested my website again against EDGE and Chrome.   Chrome is where the problem is.   (I just made sure I had the latest version).   EDGE does not have a problem, even without my altering any settings.

  *   Gideon

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by tenacex** [comment] 2018-07-19 21:48
Hi @gidmeister2, if it is chrome then that is expected behavior. This is due to their autoplay policy and we have no control over this. Sorry! Going to close this as it is out of our control.

**Closed by tenacex** 2018-07-19 21:48 UTC
