### ISSUE TITLE
error - ReferenceError: EventTarget is not defined

### ISSUE THREAD

**Issue by Jairwin-L** [vimeo/player.js#937] opened 2023-06-02 04:08 UTC
install using pnpm, then pnpm dev
<img width="956" alt="image" src="https://github.com/u-wave/react-vimeo/assets/32570960/1171e355-bf9e-430b-8263-0d94db7ddacb">
env info
```bash
"@vimeo/player": "^2.20.1",
"react": "18.2.0",
"react-dom": "18.2.0",
```

guess there might be something wrong here: https://github.com/vimeo/player.js/blob/master/src/lib/functions.js#L117

**Comment by salmoro** [comment] 2023-06-02 14:56
@Jairwin-L I was unable to reproduce this issue.

See the following Stackblitz which has React and @vimeo/player and all seems to work well.
https://stackblitz.com/edit/stackblitz-starters-nmzj5j?file=src%2FApp.tsx

If you can help us reproduce this issue or if you can provide more details about your setup and code we'd be happy to investigate further.

**Comment by Jairwin-L** [comment] 2023-06-05 02:53
let me think about it

**Comment by Jairwin-L** [comment] 2023-06-08 02:19
@salmoro I re-reproduced this problem. It seems to be because of the node version. There are two node versions on my computer: 14.19.3 and 18.0.0. The 14 version will have this error, and the 18 version will not

**Comment by rs-r2d2** [comment] 2023-11-03 12:06
If I rollback vimeo/player version 2.18.0 it works with server side with node 14.18

**Comment by bdougherty** [comment] 2024-04-03 17:59
Not sure what happened in 2.19 to break it, but I'm going to close this one out because Node 20 is now the LTS version.

**Closed by bdougherty** 2024-04-03 17:59 UTC
