### ISSUE TITLE
Performance Google Lighthouse

### ISSUE THREAD

**Issue by Integral-design-marketing** [vimeo/player.js#630] opened 2020-09-20 18:38 UTC
### Expected Behavior
Performance Google Lighthouse
### Actual Behavior
"Consider marking your touch and wheel event listeners as `passive` to improve your page's scroll performance."
### Steps to Reproduce
https://web.dev/uses-passive-event-listeners/?utm_source=lighthouse&utm_medium=devtools

**Comment by luwes** [comment] 2020-09-30 17:52
Duplicate of #553

**Closed by luwes** 2020-09-30 17:52 UTC
Labels: enhancement, player
