### ISSUE TITLE
Add controls:false option (or allow background:true, muted:false)

### ISSUE THREAD

**Issue by evvvritt** [vimeo/player.js#234] opened 2018-04-13 15:48 UTC
Hi, we'd like to use our own custom UI buttons to control our vimeos. 

`background:true` achieves this but also plays muted. But on iOS, as you [note in your docs](https://github.com/vimeo/player.js#setvolumevolume-number-promisenumber-rangeerrorerror), you can't _unmute_ the video via `setVolume(1)`. So you're stuck with muted videos.

Please provide a separate `controls:false` option. (or allow `background:true`, `muted:false`)

Then hopefully, following [Webkit's guidelines](https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/) – autoplay-unmuted would fail and you could show your own custom play button to start playback with sound.

> Don’t assume a media element will play, and don’t show the pause button from the start. Look at the Promise returned by the play function on HTMLMediaElement to see if it was rejected:

Related Issue – #227 

Thank you for providing this library but please bring it in step with Webkit's guidelines.

**Comment by fredlee0109** [comment] 2018-05-04 22:34
related to #197

**Comment by luwes** [comment] 2018-06-14 02:01
Duplicate of #197

**Closed by luwes** 2018-06-14 02:01 UTC
Labels: enhancement
