### ISSUE TITLE
Support for <video muted> and <video playsinline>?

### ISSUE THREAD

**Issue by willashley23** [vimeo/player.js#83] opened 2016-11-22 08:33 UTC
If we want the vimeo player to autoplay on iOS 10, the `<video>` tag must have `muted`. I've been looking through the code in the lib folder and haven't found anyway to add this property to the videos, and since they are inside an iframe, it will not be possible to use jQuery for this. Is there any way around this in the api?

**Comment by bdougherty** [comment] 2016-11-22 17:40
Duplicate of #76. Please see my comment there.

**Closed by bdougherty** 2016-11-22 17:40 UTC

**Comment by JSteunou** [comment] 2017-09-22 14:36
@bdougherty a lot of people is asking on different thread on the forum, since years, but vimeo has not move...
A good video provider should listen API users / developers if it wants its services to spread more than the others.
