### ISSUE TITLE
Player vimeo controls issue in app browser 

### ISSUE THREAD

**Issue by rajkumarui** [vimeo/player.js#98] opened 2017-01-02 14:27 UTC
Hi, the **Vimeo player** control is hidden after play starts and doesn't show the control bar again when touched on the video. So if you can gives us the API function to **'show'** and **'hide'** the **control bar**. Lot of our issues can be solved. Please given us this feature in new version.

**Comment by bdougherty** [comment] 2017-01-03 21:26
Curious what your use case is here for showing and hiding the controls without someone interacting or making an api call that would trigger it (`setVolume` or `setCurrentTime`).

**Comment by bdougherty** [comment] 2017-01-24 20:21
Didn’t hear back, so I’m going to close this for now.

**Closed by bdougherty** 2017-01-24 20:21 UTC

**Comment by Sunakujira1** [comment] 2018-02-16 16:22
Hello,

I was having this exact same problem on Android WebView on React Native, and got it fixed so here are my findings.  
1. There is a warning on the console of WebView that says at Line 18 of `player.js` located at [https://f.vimeocdn.com/p/2.68.16/js/player.js](https://f.vimeocdn.com/p/2.68.16/js/player.js):  
`[Deprecation] 'HTMLVideoElement.webkitSupportsFullscreen' is deprecated. Please use 'Document.fullscreenEnabled' instead.`
when the problem will/do occurs.

2. Changing the user agent stops this warning to show up, and the issue does not occur.

3. User agent containing term `Android` seems to cause the issue. For example, my user agent is `Mozilla/5.0 (Linux; Android 7.1.1; ONEPLUS A5000 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.137 Mobile Safari/537.36` but when I remove the `Android` from it, it works fine.

From this in mind, setting user agent as simple as `" "` fixes this problem as well.

So to me it seems like an issue caused by the actual Vimeo player's code (not in this library), which seems to be doing a lot of things with user agent.
It'll be great if we can get some insights from someone who is familiar with the `player.js`.

**Comment by zeusstl** [comment] 2019-05-05 20:40
The same Deprecation message is still showing.

@bdougherty: To clarify what the op was saying...
The control bar completely vanishes. As in, tapping on the video does not bring back the control bar. Once it hides the first time, it's gone forever and only returns if you reload the player.

@Sunakujira1's solution is a hack and not a real fix of the problem.

Can't the codebase be updated to follow the Deprecation recommendation to "Please use 'Document.fullscreenEnabled' instead."

**Comment by zeusstl** [comment] 2019-05-08 16:32
I've tried to implement @Sunakujira1's solution, but can't recreate the desired effect.

**Comment by bramski** [comment] 2021-01-28 22:34
I have this issue. Only in Android. Changing the userAgent to "" has zero effect.
