### ISSUE TITLE
Vimeo Player Stuck Loading

### ISSUE THREAD

**Issue by Hanley1** [vimeo/player.js#842] opened 2022-06-24 13:30 UTC
### Expected Behavior

Video plays

### Actual Behavior

Video gets stuck in loading process, showing endless circle animation

### Steps to Reproduce

I have a user reporting this issue when they try to load videos on our site. 

Example: Go to  www.audiblegenius.com/course/bb1/section_1/drums_1/earned, hit the play button.

We cannot recreate it on our end. He's experiencing it only with Firefox and Brave, Chrome works fine. And he's getting an error in the console. See screenshot:

![Screenshot](https://user-images.githubusercontent.com/4249137/175546083-9d5d9251-bfe3-4f38-a6d3-c6a4f38b5df6.png)

**Comment by giacomelli** [comment] 2022-06-27 09:33
Same here!

We have reports from our users with the same problem behavior, most of the reports are about Chrome.

I've tested it on my Windows machine and it's happening with some videos:
![image](https://user-images.githubusercontent.com/177389/175908249-43008ba8-b5c7-443a-9000-dca9ab257391.png)

**Comment by giacomelli** [comment] 2022-06-27 11:16
From the messages is pretty clear that is something related to Google QUIC protocol.

When I disabled it on Chrome, the error stopped:
![image](https://user-images.githubusercontent.com/177389/175929149-63c87a8e-9c66-4eff-9a58-83fe14353c5a.png)

**Comment by DiegoPiloni** [comment] 2022-06-27 16:29
Thanks a lot @giacomelli !! We were having several user reports because of this and your solution seems to be working for all of them

**Comment by Hanley1** [comment] 2022-06-27 18:44
Thanks @giacomelli!

**Comment by Hanley1** [comment] 2022-06-27 19:03
Thanks @giacomelli

This takes care of Brave as well since it's built with Chromium. 

As for Firefox apparently they rolled out QUIC protocol in a recent update. It can be disabled by disabling http3: https://securityboulevard.com/2022/01/easy-firefox-fix-of-the-day-disable-http3/

**Comment by Hanley1** [comment] 2022-06-27 20:54
Well I take it back about Firefox. After disabling http3 my user is still experiencing this issue. Any ideas on how to prevent the error in Firefox?

**Comment by dario-santandrea** [comment] 2022-06-29 00:14
Hi! Any update about this issue? I have a lot of angry customers because their videos won't play. Thanks!

**Comment by dario-santandrea** [comment] 2022-06-29 13:05
In case anyone is interested.

We solved the problem using direct links to videos (https://vimeo.zendesk.com/hc/es/articles/224823567-Direct-links-to-video-files) via the vimeo API and loaded the video with the Plyr.io player (https://plyr.io/)

So far we have had no complaints from our customers 😄

**Comment by rkrishnan8594** [comment] 2022-06-29 13:23
Providing a followup to this issue - we've confirmed with one of our CDN partners that this error on video segment requests was caused by a recent Chrome update. We'll be in close communication with them about an expected resolution timeline (the fix for this will very likely not be on the Vimeo side).

In the interim, our recommendation is for users to switch browsers if they're encountering this issue.

**Comment by rkrishnan8594** [comment] 2022-06-30 19:45
We've confirmed with our CDN partner that this issue is now resolved.

**Closed by rkrishnan8594** 2022-06-30 19:45 UTC

**Comment by rkrishnan8594** [comment] 2023-06-14 13:28
@alexeevit Thanks for the report. This sounds like a different issue than the one reported in this thread. Do you mind filing a new issue for this and including a JSFiddle or CodePen that we can use for reproduction?

**Comment by alexeevit** [comment] 2023-06-14 17:12
@rkrishnan8594 Unfortunately, I cannot reproduce it in a clean environment. It seems that it conflicts with something on my website. Don't event know where to start, probably I should turn off all the external scripts and start connecting them 1 by 1.

**Comment by yrletter** [comment] 2023-06-16 22:52
Similar issue:

https://native-2e3564-bdcdb6ca2f13f1fa287c207f4.webflow.io/directors/clara-aranovich-valdes

I have an ongoing issue in Webflow where the Vimeo loading spinner keeps appearing over videos that are autoplaying. It's hard to pinpoint as it only happens intermittently. Try clicking "play" on a few videos, usually it happens after a few. I have written custom js that keeps track of the vimeo videos and modal windows. Any ideas for how to troubleshoot?

**Comment by alexeevit** [comment] 2023-06-19 09:09
Gotta say that in my case I use webflow as well

> I ran into this issue the other day again. In my case it's not related to the QUIC protocol (no errors in console and I disabled the flag in chrome). I implemented autoplay for modal windows — once the modal window is displayed (removed `display: none`), I initialize the player, wait until it's ready and play:
> 
> ```
> $('[data-name=demo-video]').on('showed', function(event) {
>     var videoPlayer = new Vimeo.Player('demo-player');
>     videoPlayer.ready().then(function() { videoPlayer.play(); });
> });
>   
> $('[data-name=demo-video]').on('hidden', function(event) {
>     var videoPlayer = new Vimeo.Player('demo-player');
>     videoPlayer.ready().then(function() { videoPlayer.pause(); });
> });
> ```
> 
> So sometimes (like every 10 time) it's playing the video but still displaying the loading spinner. Looks like some kind of race condition.
> 
> I tried to replace `.ready()` with `.on('loaded')` and it started appearing even more often.
> 
> What's interesting, I cannot reproduce it if I use adblock.

**Comment by toddpadwick** [comment] 2023-07-17 11:26
Hi @rkrishnan8594 . Unfortunately, we still seem to be experiencing this issue on, the latest Chrome release as of 17th July 2023: Version 114.0.5735.198 (Official Build) (x86_64).

![Screenshot 2023-07-17 at 12 24 46 (2)](https://github.com/vimeo/player.js/assets/36191462/220a8210-a9bb-421d-86cf-ca6bef267dc9)

**Comment by rkrishnan8594** [comment] 2023-07-17 15:39
@toddpadwick Are you seeing an `ERR_QUIC_PROTOCOL_ERR` in your console logs? If not, please file as a separate issue. And if it doesn't appear to be an issue with the Player.js SDK, please report this as an issue to [Vimeo Support](https://vimeo.com/help/contact).

**Comment by brandonhrowe** [comment] 2023-08-15 13:29
@rodox12 Per the note above, please report this as a separate issue to [Vimeo Support](https://vimeo.com/help/contact) as this sounds different than the QUIC issue.

**Comment by rkrishnan8594** [comment] 2023-08-15 13:30
The root cause of this issue (Chrome bug) has been fixed. If you're experiencing unusually long re-buffering that seems to be caused by this library, please file a new issue in this repo. If seemingly unrelated to this library, please contact [Vimeo Support](https://vimeo.com/help/contact).
