### ISSUE TITLE
Window Load Vimeo Autoplay

### ISSUE THREAD

**Issue by a25814740** [vimeo/player.js#246] opened 2018-05-10 03:12 UTC
### Expected Behavior
I hope it can autoplay when window onload.

### Actual Behavior
It work ! But it work just a moment ...

### Steps to Reproduce
I've included a codepen here
https://codepen.io/lovelincoding/pen/bMaVOZ

Sorry, I'm a novice programmer, I hope the God can help me ...

**Comment by jybleau** [comment] 2018-05-10 16:16
@a25814740 , this problem has been mentionned in #243 and is also linked to #242 regarding recently updated browser's autoplay policy (and inconsistency across browsers too).

Best practice would be to simply use the `autoplay`property and let the browser choose to play it or not.
If it does not autoplay, then the user will have to interact with the video.

**Comment by a25814740** [comment] 2018-05-11 10:37
OK, I found my problem. Thanks.

**Comment by danrossi** [comment] 2018-05-12 17:02
To save duplicating comments here is my comment on another ticket. muted has no effect at all. Should be able to detect an autoplay hanging problem and mute then try to play again. 

Perhaps getPaused might work but there is no pause event. Its in a play toggled state when it hangs. 

https://github.com/vimeo/player.js/issues/242#issuecomment-388567363

**Comment by danrossi** [comment] 2018-05-12 17:06
Even if it hangs the very first time. The second load should begin autoplay instantly. Vimeo is just hanging regardless.

**Comment by luwes** [comment] 2018-05-14 23:43
Duplicate of #242

**Closed by luwes** 2018-05-14 23:43 UTC
