### ISSUE TITLE
Any events (Play, Pause and Loaded...) aren't fired on live recurring events

### ISSUE THREAD

**Issue by iseki-masaya** [vimeo/player.js#586] opened 2020-06-17 04:15 UTC
### Expected Behavior
To be able to fire events on live recurring events.

### Actual Behavior
The callback of player.on is not called when player starts to play or pause.

```
const player = new Player("video", {
  url: "https://vimeo.com/event/XXXXXX",
});
player.on('play', function() {
  console.log('Play event is not fired.');
});
player.on('pause', function() {
  console.log('Pause event is not fired.');
});
```

### Steps to Reproduce

1. Create a recurring stream in Vimeo.
1. Copy URL.
1. Add the URL for the player build.
1. Display on page and play or pause a player.

**Comment by luwes** [comment] 2020-06-21 16:42
Duplicate of #493

**Closed by luwes** 2020-06-21 16:42 UTC
