### ISSUE TITLE
Live recurring events in Player.js

### ISSUE THREAD

**Issue by graphic-artisan** [vimeo/player.js#582] opened 2020-06-10 14:49 UTC
### Expected Behavior

To be able to use the ID of a recurring Vimeo livestream & a showcase with player.js.

### Actual Behavior

Player does not recognize ID for livestream or showcase embeds. 

### Steps to Reproduce

Create a recurring stream in Vimeo. 
Go to embed settings. 
Get embed code. 
Copy ID. 
Add the ID for the player build. 
Display on page or post.

**Comment by richardhasseneeg** [comment] 2020-06-24 20:09
Can you provide an update on this? We are dealing with this issue as well.

**Comment by SamuelNitsche** [comment] 2020-06-30 19:02
Seems like this was implemented. See #493.

**Comment by luwes** [comment] 2020-06-30 19:02
duplicate of #493 

note that for now the iframe embed method has to be used because the oEmbed API that retrieves the html embed code does not work with recurring live event urls.

**Closed by luwes** 2020-06-30 19:02 UTC
Labels: enhancement

**Comment by SamuelNitsche** [comment] 2020-06-30 19:07
> note that for now the iframe embed method has to be used because the oEmbed API that retrieves the html embed code does not work with recurring live event urls. 

Can this please be documented somewhere?
