### ISSUE TITLE
loadVideo doesnt call catch on error

### ISSUE THREAD

**Issue by blackmambahk** [vimeo/player.js#57] opened 2016-10-02 08:47 UTC
### Expected Behavior

The example code in the docs for loadVideo shows catching a 'PrivacyError' when loading a password protected resource.
### Actual Behavior

A catch handler never gets called
### Steps to Reproduce

If you try in the demo app to load a password protected resource it loads and displays the login screen as expected but the log shows no error output, and a breakpoint on line 409 of api-demo.js also never gets hit. 

Tried it in my own local code first and had same issue. Although the rather than display the login it displays 'unhandled privacy error'.

This also raises another question, there seems no way to create a player without first setting a video url and therefore loading it, as the player on instantiation checks the iframe for a valid source and blows up if it doesn't find one. So at the moment I have to initially set a url to a small dummy video to get the player instantiated and then to allow me later to then call loadVideo to load the actual video I want.

**Comment by BernsteinA** [comment] 2016-10-03 23:29
Does it work with a div instead of an iframe? Possible overlap with #58

**Comment by Nostrabramus** [comment] 2017-08-17 09:34
I have the same problem, I use a div not an iframe
any feedback?

**Comment by rijk** [comment] 2017-09-25 16:09
This is pretty terrible when embedding the player in a webapp. The user gets no visual feedback from the player (as it just doesn't load) about the situation, and since no error handler is called it's also impossible to give feedback via the app interface about it. Moreover, as the 'loaded' handler is never called, the application stays in loading state, completely breaking the possibility to even resolve the situation as a user.

**Comment by rijk** [comment] 2017-09-25 17:17
I discovered by chance, that you can get this to work by setting an error handler on the player. It doesn't matter what the handler does, it just needs to be there.

### Does not work:
```
this.player.loadVideo( id ).catch( this.props.onError )
```
(`this.props.onError` is never called)

### Does work:

```
this.player.loadVideo( id ).catch( this.props.onError )
this.player.on( 'error', function() {} );
```

Note that even though the handler is called, it still does not receive the `PrivacyError`. I submitted a different issue for this (#164). Gotta love this package 😅

**Comment by mirague** [comment] 2017-11-12 13:02
@rijk That's an interesting workaround you found by chance, that definitely seems like unintended behaviour for sure. One should be able to rely on `.catch()` being fed the exception regardless of an `on('error')` handler.

**Comment by rsichel107** [comment] 2018-02-27 14:01
Hi @blackmambahk, @rijk, @mirague and others- You are correct to assume that `.catch()` should work as indicated in our ReadMe documentation. This has been fixed in our latest release- thank you for your patience. Closing the issue.

**Closed by rsichel107** 2018-02-27 14:01 UTC
Labels: catch-errors, player
