### ISSUE TITLE
controls=0&background=1 parameters vimeo player show Tap to Unmute button in Chrome on mobile devices

### ISSUE THREAD

**Issue by ellafitz** [vimeo/player.js#869] opened 2022-11-01 22:32 UTC
### Expected Behavior

Expect no notice "tap to unmute" on mobile

### Actual Behavior

See screendump of mobile device / Chrome browser
![Screenshot_20221101-215735_Chrome](https://user-images.githubusercontent.com/4292251/199352881-fbe59a35-07fd-44ae-9e1c-3392ae056dd5.jpg)

Chrome browser on tablet and mobile
Mobile: if I tap it disappears
Tablet: if I tap it does not go away

### Steps to Reproduce

[www.hoteltesselhof.com](url) 

https://player.vimeo.com/video/701139886?background=1&controls=0&h=050673c94a&autoplay=1&loop=1&title=0&byline=0&portrait=0

**Comment by poulDanielsen** [comment] 2022-11-02 07:30
Also experiencing this on Firefox on desktop with simulated mobile in devtools. The other ticket for this was closed prematurely.

**Comment by liamcrean** [comment] 2022-11-02 08:58
Yes. this marked as fixed in another thread, but I still see issue (tested both Dev tools Firefox and iOS Safari so far)

**Comment by luke-hale** [comment] 2022-11-02 09:41
+1
![IMG_C36730BF3EA2-1](https://user-images.githubusercontent.com/60442292/199456361-03b73f69-7405-4d04-b036-6969fa551782.jpeg)

**Comment by wiegertschouten** [comment] 2022-11-02 12:07
Same issue here

<img width="394" alt="image" src="https://user-images.githubusercontent.com/33861354/199485704-9b86d246-a961-4017-b64d-9f0fdec96d2f.png">

Video URL used: https://player.vimeo.com/video/xxxxxxxxx?background=1

**Comment by dikodahan** [comment] 2022-11-02 13:13
Same issue here, NOT FIXED!!!

**Comment by rkrishnan8594** [comment] 2022-11-02 13:15
Thanks for reporting. Closing this issue as it's a duplicate of #867 - updates will be provided there.

**Closed by rkrishnan8594** 2022-11-02 13:15 UTC
