### ISSUE TITLE
FeatureRequest: startTime option in embed-options

### ISSUE THREAD

**Issue by fredlee0109** [vimeo/player.js#208] opened 2018-02-20 00:17 UTC
### Expected Behavior

https://jsfiddle.net/kjkcrz12/1/

I want to be able to give `startTime` option in constructing the player.

https://github.com/vimeo/player.js#create-an-embed
https://github.com/vimeo/player.js#embed-options

As a workaround, we are currently doing a one-time .setCurrentTime() on timeUpdate event

**Comment by luwes** [comment] 2018-03-02 15:01
Closing as it is a duplicate of #20.

**Closed by luwes** 2018-03-02 15:01 UTC
Labels: enhancement
