### ISSUE TITLE
TypeError when embedding player

### ISSUE THREAD

**Issue by jasonlav** [vimeo/player.js#1034] opened 2024-06-13 15:56 UTC
### Expected Behavior
Vimeo player should function without Javascript errors.

### Actual Behavior
Vimeo player throws the following error:
```
player.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at player.js:2:17262
    at Array.forEach (<anonymous>)
    at z (player.js:2:17236)
    at c._onMessage (player.js:2:26203)
```

Note that video player will still work.

### Steps to Reproduce
Run the documentation embed example in any modern browser. https://jsfiddle.net/fvewbhr0/

**Comment by diogomiguel** [comment] 2024-06-13 16:17
Here for the same issue. It seems something changed on iOS more specifically as this only became an issue today (13/06)

Using it with `react-player`
```
TypeError: undefined is not an object (evaluating 'e.href.indexOf')
  at <anonymous> @ https://player.vimeo.com/api/player.js:2:17271
  at forEach @ [native code]
  at z @ https://player.vimeo.com/api/player.js:2:17243
  at <anonymous> @ https://player.vimeo.com/api/player.js:2:26204
  ```

**Comment by weeblr** [comment] 2024-06-13 16:43
@diagomiguel not related to iOS, happening on different browsers on windows 11

**Comment by christriants** [comment] 2024-06-13 16:46
Thanks for reporting this issue. We're looking into this right now. We have identified this issue as being related to a recent release. For those impacted, please share if you're observing any behavioral impact as a result of this issue.

**Comment by abelbordonado** [comment] 2024-06-13 17:53
Hi everyone! 

My client is using this plugin and he and his users are suffering the issue. I can confirm mac (chrome) and windows chrome and Edge browsers.

Digging in the code

`````
    /**
 * Remove a stored callback for a method or event for a player.
 *
 * @param {Player} player The player object.
 * @param {string} name The method or event name
 * @param {function} [callback] The specific callback to remove.
 * @return {boolean} Was this the last callback?
 */
    function removeCallback(player, name, callback) {
        var playerCallbacks = callbackMap.get(player.element) || {};
        if (!playerCallbacks[name]) {
            return true;
        }

        // If no callback is passed, remove all callbacks for the event
        if (!callback) {
            playerCallbacks[name] = [];
            callbackMap.set(player.element, playerCallbacks);
            return true;
        }
        var index = playerCallbacks[name].indexOf(callback);
        if (index !== -1) {
            playerCallbacks[name].splice(index, 1);
        }
        callbackMap.set(player.element, playerCallbacks);
        return playerCallbacks[name] && playerCallbacks[name].length === 0;
    }
    `````
     
   The error comes from the line  `var index = playerCallbacks[name].indexOf(callback);` 1145 
   
   If you put a break point it won't happen, so it means at the moment of execution the playerCallbacks doesn't have the `name` item declared which is  value 'addEventListener`.
   
having the breakpoint probably allows some promise to resolve and actually works with no issue.

I will silence this error the moment and follow up for a solution.
   
   
 In our case is `vue-vime-plugin` which is loading th `player.module.es` (or `player.es`) not sure who download what.

**Comment by colbyalbo** [comment] 2024-06-13 19:10
I have one user experiencing this error. The video still plays.

**from my error reporting:**
undefined is not an object (evaluating 'e.href.indexOf')

**version**
 v2.23.0, https://github.com/vimeo/player.js

**Browser:**
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Safari/605.1.15

**Comment by egachi** [comment] 2024-06-13 20:09
Hello, I am also experiencing this scenario, I am using mac M1 mini using Chrome Version 125.0.6422.142. It was working fine yesterday, no change in code.

```javascript
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'indexOf')
    at player.es.js:1251:1
    at Array.forEach (<anonymous>)
    at processData (player.es.js:1250:1)
    at _this._onMessage (player.es.js:2163:1)
```

**Comment by bruce-at-events** [comment] 2024-06-14 02:03
same issue here, pls fix ASAP.

**Comment by kaeruB** [comment] 2024-06-14 02:28
Same issue, for me it happens in the following environment: 
- various browsers Chrome Version 126.0.6478.57, Safari, Edge, Firefox (seems to be not related to browser)
- macOS 14.2.1 (23C71)
- "@vimeo/player": "2.23.0"
- "react": "18.3.1",
It was working fine yesterday with the same codebase.

**Comment by andrew-turner-evt** [comment] 2024-06-14 03:17
+1 Has broken our implementation also

**Comment by tkumpanenko** [comment] 2024-06-14 06:58
+1 Same problem. How ever we use wrapper lib "u-wave/react-vimeo" around @vimeo/player.

**Comment by Nishkea** [comment] 2024-06-14 07:18
> Thanks for reporting this issue. We're looking into this right now. We have identified this issue as being related to a recent release. For those impacted, please share if you're observing any behavioral impact as a result of this issue.

Any updates on this issue? @christriants :) Sadly giving errors on a lot of our clients implementations

**Comment by dngraphisme** [comment] 2024-06-14 08:20
Same for me with webpack and import library 

`Uncaught (in promise) TypeError: can't access property "indexOf", e.href is undefined`

**Comment by abelbordonado** [comment] 2024-06-14 09:56
I ignore the error, and the video still plays.
My workaround until it is fixed.

````
 onError(error) {
      /**
       * Issue from @vimeo/player v2.20.1 that happen 14 Jun of 2024
       * Follow up: https://github.com/vimeo/player.js/issues/1034
       */
      if (error?.message.includes('Cannot read properties of undefined')) {
        return
      }  
     ````

**Comment by alexander-elder** [comment] 2024-06-14 13:24
> I ignore the error, and the video still plays. My workaround until it is fixed.
> 
> ```
>  onError(error) {
>       /**
>        * Issue from @vimeo/player v2.20.1 that happen 14 Jun of 2024
>        * Follow up: https://github.com/vimeo/player.js/issues/1034
>        */
>       if (error?.message.includes('Cannot read properties of undefined')) {
>         return
>       }  
>      ````
> ```

Be aware that the error message may differ per browser.

In Safari `undefined is not an object (evaluating 'e.href.indexOf')`

**Comment by christriants** [comment] 2024-06-14 14:00
Thank you all for your patience. We pushed out a change to resolve this. Appreciate the community reporting this issue. I am going to close this, but please feel free to file a new issue if you are still experiencing this.

**Closed by christriants** 2024-06-14 14:00 UTC

**Comment by weeblr** [comment] 2024-06-18 08:29
@christriants Any ETA for an actual publication of the fixed package?

**Comment by christriants** [comment] 2024-06-18 13:21
@weeblr The issue was introduced by a change outside of this package. Are you still experiencing a similar issue?

**Comment by weeblr** [comment] 2024-06-18 13:27
I have not checked as I was expecting an update. So you're saying no change is needed in @vimeo/player ?

**Comment by christriants** [comment] 2024-06-18 13:39
@weeblr Yes. I should have been more clear. There will be no related update to this package. And thanks again for jumping in. Please reach out with any issues or questions.

**Comment by egachi** [comment] 2024-06-18 15:18
@christriants No issues right now, any possible reason why it started to fail? Thank you!

**Comment by christriants** [comment] 2024-06-18 17:24
@egachi This was an incidental regression that occurred due to a code refactor.
