### ISSUE TITLE
Disable Seek

### ISSUE THREAD

**Issue by boxgames1** [vimeo/player.js#356] opened 2019-01-03 14:57 UTC
`player.on("seeked", function(e) {
  // cancel seek 
});`

This is a question. Is there any option of disabling the seek?  Tried some workarounds but couldn't find a solution.

**Comment by jybleau** [comment] 2019-01-03 20:44
Hi @boxgames1 

**This may help you:**
https://jsfiddle.net/jybleau/zes4hbdd/

It uses the Video object directly but it can be translated to the Vimeo API using `timeupdate`, `seeked` and `ended` events.

It also uses the `video.played` property but this is not (yet ?) implemented in the Vimeo player API. `played` allows to seek only within what is already watched. It can be ignored or you can try to track it by yourself; depends on your requirements.

**Those 2 issues are related to your question too** 
https://github.com/vimeo/player.js/issues/245
https://github.com/vimeo/player.js/issues/40

PS: I was planning to adapt it for the Vimeo player... when one of our clients would require it.

**Comment by boxgames1** [comment] 2019-01-04 08:49
@jybleau Thanks.

I already have developed a workaround for HTML5 videos. I wasn't able to find a solution for vimeo videos.

The most intriguing part is when user drags the timepoint. If I stop the video it gets crazy and drop never happens.

The biggest difference between Vimeo and HTML5 videos is that one uses "seeked" while the other uses "seeking". Not the same. Plus, using setCurrentTime fires again "seeked".

**Comment by jybleau** [comment] 2019-01-07 20:07
I see... 
Would have been too easy. I'll give it a try, maybe it could help formulate a feature request.

**Comment by boxgames1** [comment] 2019-01-08 08:21
@luwes Do you have in mind to develop this feature in a near future?

All possible workarounds are terribles in UX terms.

**Comment by luwes** [comment] 2019-01-10 01:30
Thanks for the feedback @boxgames1!

We'll definitely consider making properties available that could be a help for this.
I'll let the player team know.

**Comment by luwes** [comment] 2019-01-10 01:32
I see this is a duplicate of #61. Closing here.

**Closed by luwes** 2019-01-10 01:32 UTC
Labels: question
