### ISSUE TITLE
Event listener not triggered after changing iframe and new player initialized with react

### ISSUE THREAD

**Issue by donni106** [vimeo/player.js#152] opened 2017-08-10 18:16 UTC
When my page is rendered there is a Vimeo player autoplaying correctly with an 'play' and 'ended' event listener initialized. The events are firing correctly. I have then three other clickable images, which are overloading the first rendered Vimeo player. I change the video component on image click.

```
<div className="video-stage" ref="videoStage">
  <div className="video-responsive">
    <iframe src={src} width="1600" height="900" frameBorder="0" allowFullScreen />
  </div>
</div>
```

So the iframe src gets updated.

### Expected Behavior

The Vimeo player is reloaded with a new video. The video can be watched. The event listeners are bound again to the new player. 'play' and 'ended' should be triggered again.

### Actual Behavior

The Vimeo player is reloaded with a new video. The video can be watched. The event listeners are not bound again to the new player. 'play' and 'ended' will not be triggered.

### Steps to Reproduce

This code runs after updating the video component with a new src:

```
if (findDOMNode(this.refs.videoStage)) {
  const videoIframe = findDOMNode(this.refs.videoStage).querySelector('iframe');

  if (videoIframe) {
    console.log(videoIframe);

    const player = new VimeoPlayer(videoIframe);

    player.ready().then(() => {
      player.on('play', data => console.log(data));
      player.on('ended', data => console.log(data));
      console.log(player);
      player.play();
    });
  }
}
```

`console.log(videoIframe);` is correctly giving the new iframe node.
`console.log(player);` is correctly giving infos about the new outerHTML node, which is the new iframe.
`player.play();` correctly plays the video.
'play' and 'ended' are not triggered.

I tried with different solutions on different times. With timeouts and without. With `player.ready()` and without. Nothing helped me out.

I don't know how to get a real new fresh working VimeoPlayer instance.

I am using react 15.4.0 and @vimeo/player 2.1.0.

**Comment by luwes** [comment] 2018-03-02 19:10
Duplicate of #126. We will look at this soon.

**Closed by luwes** 2018-03-02 19:10 UTC
