### ISSUE TITLE
Autopause not working in Firefox & chrome

### ISSUE THREAD

**Issue by stmaheswari** [vimeo/player.js#714] opened 2021-05-07 08:08 UTC
### Expected Behavior
When have multiple videos on same page , click on 1st one and then next 2nd one. Now the 1st video should be paused but its not  happening. 

### Actual Behavior
Until pause it manually it plays when have multiple videos.
### Steps to Reproduce
I have two videos in my div

<div>
 <iframe src="https://player.vimeo.com/video/3228167748?title=0&byline=0&portrait=0&speed=0" width="408px" height="500.338" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
  <iframe src="https://player.vimeo.com/video/3511352761?title=0&byline=0&portrait=0&speed=0" width="408px" height="500.338" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

**Comment by fisherinnovation** [comment] 2021-05-08 01:34
Thanks for reporting! This has been ticketed for review and fix.

**Comment by ofmarconi** [comment] 2021-05-21 18:14
Helo!

Is there any solution for this? I'm working with tabs, so the user has to click on a button to change tabs.

How can I assign the button to pause all videos? Every time an ID or Class is clicked pausing all the videos on the page, is this possible with the API?

**Comment by fisherinnovation** [comment] 2021-05-24 21:12
This issue is being reviewed by the engineering team and a fix is in the works. I will ensure this thread is updated when the solution is public facing.

**Comment by RL-av** [comment] 2021-08-05 10:17
@fisherinnovation

any news on this?

**Comment by ChazyTheBest** [comment] 2021-11-05 17:48
We just got Vimeo premium and we're facing this same issue.

Any news on this?

**Comment by ltbmedia** [comment] 2022-01-19 11:49
Hi @fisherinnovation

Is there any update on this as it's still an issue?

**Comment by PeterVermeulen** [comment] 2022-02-03 15:58
autopause not working on Mac OSX Big Sure, Chrome Version 98.0.4758.80 (Official Build) (x86_64)

**Comment by phoshenwen** [comment] 2022-05-06 17:46
I'm sure everyone is aware, but for completeness-sake it's also a problem on Win 10 with Chrome v100.0.x.

Got a hero video which does not pause when a modal video starts playing.

**Comment by ofmarconi** [comment] 2022-07-14 23:45
vimeo is tr*sh

**Comment by rkrishnan8594** [comment] 2022-07-15 03:19
It would be helpful if someone experiencing this issue could provide a reproducible example. Here's one that I set up using the embed code from OP (but with new clips, as those ones have been deleted): https://jsfiddle.net/rowankrishnan/tpdga0jh/1/

Unable to reproduce this issue on Chrome 103.0.5060.114 or Firefox 102.0.1.

**Comment by ofmarconi** [comment] 2022-07-15 03:52
@rkrishnan8594  https://www.loom.com/share/7e5b41230e0a4583acb250c7997a694d

**Comment by rkrishnan8594** [comment] 2022-07-15 03:54
@ofmarconi What OS (+ version) are you using?

**Comment by ofmarconi** [comment] 2022-07-15 11:45
![image](https://user-images.githubusercontent.com/6594795/179216945-f057f658-0d4a-422f-bd86-c5b48e3224e5.png)


thx

**Comment by rkrishnan8594** [comment] 2022-07-15 13:37
Thank you. We will take a look at this issue next week.

**Comment by rkrishnan8594** [comment] 2022-07-26 03:38
@ofmarconi We're not able to reproduce this bug on Windows 10 running Chrome 103. It might be worth confirming your cookie settings in Chrome, as blocking third party cookies under some or all contexts would lead to autopause functionality not working.

**Comment by ofmarconi** [comment] 2022-07-26 12:44
@rkrishnan8594 thanks for investigating, I did another test, in all browsers I have here, none except chrome have some kind of extension, all "virgin"

https://www.loom.com/share/b84c8e6f45b24aca86b49b23cda43c8b

And all with the same issue.

Do you need more information?

I also tested it on another notebook with Windows 10 and the same thing, the two videos are played simultaneously.

**Comment by rkrishnan8594** [comment] 2022-07-26 13:55
@ofmarconi We'll be doing some more testing internally; I'll let you know whether we're able to confirm the issue.

**Comment by rkrishnan8594** [comment] 2022-07-26 18:08
We tested Chrome, Firefox, and Edge on an actual machine running Windows 10 (as opposed to a simulator) and are still not able to reproduce this issue. Here's the screen recording of our test in Chrome: https://vimeo.com/733694733/29252a274a

At this time, there's not much else that we can do to reproduce the issue. I will leave this issue thread open for posterity, but for anyone experiencing this issue, I would encourage you to ensure that you are not blocking 3rd party sites from using cookies or local storage, as that would break autopause functionality.

**Comment by alitan** [comment] 2023-01-07 16:55
Apparently Edge and some other browsers blocking this functionality because of Tracking prevention. I am assuming more and more browsers will adopt this and it will be more of a problem. When i disabled "Tracking Prevention" autopause is magickly working. About @ofmarconi point, is there a way to remotely pause iframe videos like vimeo player through javascript? Maybe we can patch this with other means. Thank you.

**Comment by davidwebca** [comment] 2023-06-30 22:24
We have the same issue here on all browsers with a customized player using the library.

**Comment by dar1** [comment] 2023-08-16 03:25
It's August 2023, and I just ran into this same issue of autopause still not working in Chrome (works fine in Edge and in FF).  Two embedded vimeo videos will play at same time without stopping each other.  I have 3rd party cookies enabled.  I was able to make autopause work by turning off "do not track" in Chrome. So, since do not track is frequently enabled by users, this is a problem that still needs to be fixed.  I have not seen Vimeo indicate whether or not they tested with do-not-track turned on when they claimed they could not reproduce the problem.  This needs to be fixed, or some workaround provided -- and Vimeo needs to understand that it's more than just having 3rd party cookies enabled --- do-not-track also needs to be turned off, which makes autopause effectively unusable as-is since this is not a reasonable setting to expect from users. 
I'm running Chrome 115, Windows 10 Pro, version 22H2

**Closed** 2023-08-16 16:57 UTC
Labels: bug
