### ISSUE TITLE
Broken when used with r.js optimizer

### ISSUE THREAD

**Issue by adambiggs** [vimeo/player.js#36] opened 2016-08-03 19:59 UTC
### Expected Behavior

The library should work after optimizing using the Require.js [r.js optimizer](https://github.com/requirejs/r.js).
### Actual Behavior

Works fine during development when loaded directly via Require.js, but after optimizing code into a single file using r.js, the following error is thrown:

```
Uncaught Error: Mismatched anonymous define() module: function () { 'use strict'; ...
```
### Steps to Reproduce

Process this library with r.js.

---

After some digging, it seems the issue is caused by the nested anonymous `define()` that Rollup creates when including the `native-promise-only` module. Manually deleting this code and re-running the optimizer fixes the error (but obviously this isn't a real solution).

**Comment by bdougherty** [comment] 2016-08-08 16:08
@adambiggs do you think you can dig into this further? I've never used the r.js optimizer. If not, can you provide an example project we can use to try to figure something out?

**Comment by bdougherty** [comment] 2017-01-25 00:01
Never heard back, so I’m going to close this.

**Closed by bdougherty** 2017-01-25 00:01 UTC

**Comment by Sothos** [comment] 2017-04-03 17:47
I've encountered the same issue. The problem is here in player.js:

`/*! Native Promise Only
    v0.8.1 (c) Kyle Simpson
    MIT License: http://getify.mit-license.org
*/

(function UMD(name, context, definition) {
	// special form of UMD for polyfilling across evironments
	context[name] = context[name] || definition();
	if (typeof module != "undefined" && module.exports) {
		module.exports = context[name];
	} else if (typeof define == "function" && define.amd) {
		define(**<<<MISSING MODULE NAME>>>**, function $AMD$() {
			return context[name];
		});
	}
`
