### ISSUE TITLE
On mobile the player shows the "Tap to unmute" button even when controls are disabled

### ISSUE THREAD

**Issue by christiandewit** [vimeo/player.js#868] opened 2022-11-01 22:25 UTC
### Expected Behavior
The mobile player doesn't show the "Tap to unmute" button when the video is muted, playing and controls are disabled

### Actual Behavior
The mobile player is showing the "Tap to unmute" button when the video is muted, playing and controls are disabled.

### Steps to Reproduce
See https://codesandbox.io/s/weathered-firefly-fxrzux for an example.

For desktop you need to switch the desktop browser to mobile emulation to see the issue.

<img width="603" alt="image" src="https://user-images.githubusercontent.com/3104561/199353152-326589df-3c39-41d4-91df-dc9fab90f6c9.png">

Note: This issue seems to be related to https://github.com/vimeo/player.js/issues/866 as it appeared at the same time but was not resolved after that issue was closed.

**Comment by rkrishnan8594** [comment] 2022-11-01 22:26
Thanks for reporting. Closing as this issue is a duplicate of #867.

**Closed by rkrishnan8594** 2022-11-01 22:26 UTC
