### ISSUE TITLE
'ended' event not fired and incorrect play button state if a video that has automatically started playing because of 'seek' reaches the end

### ISSUE THREAD

**Issue by stefan-hausmann** [vimeo/player.js#62] opened 2016-10-05 16:11 UTC
### Expected Behavior
we load a video into the player and, without starting it explicitely, seek into it by clicking on the player timeline (as documented correctly, this automatically starts playback). As soon as the video reaches the end, we expect an 'ended' event to be fired AND the play button to change back to the 'play' icon.

### Actual Behavior
'ended' event is not fired and the play button keeps in incorrect 'playing' state, i.e. displaying the 'pause' icon, although no video is playing anymore.

### Steps to Reproduce
see above

**Comment by nextend** [comment] 2016-10-18 06:51
The same happened for me when I upgraded my code from Froogaloop to this new library. I had to remove the api and player_id parameters from my legacy url and it worked fine :)
Old url: //player.vimeo.com/video/345345345?**api=1**&autoplay=0&**player_id=n2-ss-552item1_video**&title=0&byline=0&portrait=0&color=00adef&loop=0

**Comment by bdougherty** [comment] 2016-10-18 17:53
@nextend yep, that's the first thing mentioned in the [migration doc](https://github.com/vimeo/player.js/blob/master/docs/migrate-from-froogaloop.md).

As far as the `ended` event not firing sometimes, we're aware of the issue and have a fix coming soon. Sounds like that is what you're reporting here, @stefan-hausmann, so I'm closing this as a duplicate of #34.

**Closed by bdougherty** 2016-10-18 17:53 UTC
