### ISSUE TITLE
autoplay ignored in loadVideo()

### ISSUE THREAD

**Issue by leolux** [vimeo/player.js#359] opened 2019-01-09 21:24 UTC
The video seems to start playing automatically after invoking `player.loadVideo(id).then(...)` altough the player has been initialized with `{autoplay: false}`

Why does the event "timeupdate" gets fired after loading the video in a player that should not autoplay?

**Comment by luwes** [comment] 2019-01-09 21:49
Could you provide a jsfiddle or something similar?

A `loadVideo` call in itself should not automatically playback the video,
only when it was playing before I believe.

See https://player.vimeo.com/api/demo and load a random clip e.g. `24`

**Comment by luwes** [comment] 2019-01-09 22:11
Duplicate of #42

**Closed by luwes** 2019-01-09 22:11 UTC
