### ISSUE TITLE
Vimeo video is getting stuck in app while play properly in Android webview

### ISSUE THREAD

**Issue by jhso-dev** [vimeo/player.js#621] opened 2020-08-27 03:34 UTC
Hi @luwes ,
When two or more vimeo players are played on a web page in **Android Webview** but everything works ok in in-app browser.
I'd like to share this video https://drive.google.com/file/d/1aAZMmQrqMVEi9XS7kZ1WkDfEYZP5XgIK/view?usp=sharing

and you can also test with urls below.
- https://m.zigbang.com/catalog/78674/17/hogangnono
- https://sp.zigbang.com/catalog/36387/21/zigbang

plus If you don't mind, can you let me know the latest update?
I think It worked ok a month ago.

Thanks in advance!

#617

**Comment by luwes** [comment] 2020-08-27 13:59
Duplicate of #617

**Closed by luwes** 2020-08-27 13:59 UTC
