### ISSUE TITLE
Player Vimeo doesn't change video as expected

### ISSUE THREAD

**Issue by Nostrabramus** [vimeo/player.js#97] opened 2016-12-29 10:38 UTC
Hello,
as indicated by the Vimeo support I submit here the following:

### Expected Behavior
Changing the video id and play the new video on ended event

### Actual Behavior
It changes the video normally until the mouse pointer go over the player, in this case it set the volume to 1 (because my js library does it) but after this it doesn't fire the ended event anymore

### Steps to Reproduce
http://www.mediakey.tv/
the video is on the left top of the page

my js library is here:
http://www.mediakey.tv/typo3conf/ext/aip_vimeo/Resources/Public/js/aip_vimeo.js

**Comment by bdougherty** [comment] 2017-01-03 21:27
Seems like a duplicate of #34.

**Closed** 2017-01-24 20:22 UTC
