### ISSUE TITLE
 Events don't work

### ISSUE THREAD

**Issue by jrglaber** [vimeo/player.js#1031] opened 2024-05-17 15:11 UTC
I am loading the private video within the platform, but after loading the play, pause, ended and other events are not called correctly.

Below is my code for you to see:

```
<div :id="'video-vimeo-' + codigo" :class="embededClass ? 'embeded-video' : null" />
```

```
this.$nextTick().then(() => {
      ler player = new Player('video-vimeo-' + this.codigo, {
          id: this.codigo,
          width: this.width,
          height: this.height,
          loop: false
      })
      player.on('play', event => {
          console.log('play')
          this.$emit('play', event)
      })
      player.on('pause', event => {
          console.log('pause')
          this.$emit('pause', event)
      })
      player.on('ended', event => {
          console.log('ended')
          this.$emit('ended', event)
      })
      player.on('timeupdate', event => {
          console.log('timeupdate')
          this.$emit('timeupdate', event)
      })
  })
```

**Comment by paulovictor237** [comment] 2024-05-17 17:16
events are not working on react native webview too

**Comment by roemermt** [comment] 2024-05-17 17:36
Seeing the same issue for vue-ionic ios builds. Fine in the browser but not in ios.

**Comment by geoff-compknowhow** [comment] 2024-05-17 17:36
Our app is having the same issue.

On iOS devices, events are not being fired for the embedded player SDK.
Events are working correctly on Android devices, and in the browser.

According to our customers, this issue started happening around yesterday afternoon.

**Comment by frausto** [comment] 2024-05-17 17:51
Same issue we are seeing here

**Comment by petrklus** [comment] 2024-05-17 17:55
Also not seeing events being fired - in our case it's in the browser (Chrome tested)

**Comment by jrglaber** [comment] 2024-05-17 18:03
I call in vue web browser app. In localhost work correctly, but when build for production, don't work more.

**Comment by rkrishnan8594** [comment] 2024-05-17 18:03
Thanks for reporting this issue. We're looking into this right now. For those encountering this issue in a web browser, can you provide steps for reproduction?

**Comment by jrglaber** [comment] 2024-05-17 18:19
My system is for distance learning, so you need to be logged in to view it.  But if someone here can get public access for you to test....

**Comment by gratzc** [comment] 2024-05-17 18:25
Seeing this issue as well

**Comment by kristianm** [comment] 2024-05-17 18:28
We are encountering the same issue with events not being emitted in WKWebView. To help with diagnosing the problem, we have published a [repository where this scenario can be reproduced](https://github.com/imrse/cap-app).

From our investigation, it seems that the issue is not with the Vimeo player itself, but with the javascript assets loaded by Vimeo's iframe. We hope that someone from Vimeo finds this issue and prioritizes a fix.

**Comment by jdreetz** [comment] 2024-05-17 18:30
For anyone that is seeing this issue **not** in an iOS app, could you put together and share a Code Pen (or similar), and list the environment the failure occurs in?

**Comment by jdreetz** [comment] 2024-05-17 19:01
We just pushed an update that we think will resolve the issue. Let us know if you're still seeing it.

**Comment by jrglaber** [comment] 2024-05-17 19:22
Its work now 🥳🥳🥳🥳🥳

**Comment by geoff-compknowhow** [comment] 2024-05-17 19:45
Everything is working as expected now.

Thanks Vimeo team!

**Comment by gratzc** [comment] 2024-05-17 19:46
Working now, thanks team

**Comment by jdreetz** [comment] 2024-05-17 19:48
Thanks for reporting the issue everyone! If anyone has a test case they can share, that was reproducing the issue previously, we'd appreciate it if you could post it here. Thanks!

**Comment by lipflip** [comment] 2024-05-22 12:39
We also had this issue since last friday. Events were not working (Chrome & Firefox).
Indeed fixed now. Thank you

**Closed** 2024-06-19 23:32 UTC
