### ISSUE TITLE
Player embeds that error can not be assigned a new video

### ISSUE THREAD

**Issue by mattLummus** [vimeo/player.js#91] opened 2016-11-30 21:22 UTC
### Expected Behavior
We embed a player with the inlined html 'data-vimeo-id' attribute, i.e:
```i.e. 
<div id='player1' data-vimeo-id='1234'>
var idPlayer = new Vimeo.Player('player1')
```

If it errors (corrupted or bad permissions) we then show an error message to the user.
They can select another video from a link on the same page and we try to reinitialize the player.

We expected this to create a new player with the new video the user selected that isn't corrupted and is permitted to be embedded.

### Actual Behavior
During the attempt to create another player, we tried 2 different solutions:
 - to update the html attribute and then attempt to embed the player
-  to remove that attribute from the html element altogether and just pass the vimeo-id into the constructor via JS

In either case, the player errors again saying that the video cannot be embedded, but it is using the old (bad) video id instead of the new video we want to embed.

### Steps to Reproduce

Here are three test cases. 
- The first has a working initial embed and behaves as expected. 
- The others have a broken embed which demonstrates the issue we are encountering.
- The second attempts to set a new video via `player.loadVideo('1234')`
- The third tries to construct a new player with `new Vimeo.Player('player', {id: '1234'})`

- [Working Embed:](http://codepen.io/mattLummus/pen/yVvBwK) 
- [Broken Embed (loadVideo):](http://codepen.io/mattLummus/pen/bBLGYv)
- [Broken Embed (new Vimeo.Player):](http://codepen.io/mattLummus/pen/MbQWVR)

**Comment by bdougherty** [comment] 2016-11-30 21:25
I think this is a duplicate of #56

**Comment by mattLummus** [comment] 2016-11-30 21:31
Hmm, we are actually able to catch the error, i.e:

```
vimeoPlayer.ready().then(function () {
  // Do Stuff
})
.catch(function (error) {
  // This error is telling us that it is trying to use the same (bad) video id instead of the new one
});

**Comment by mattLummus** [comment] 2016-12-02 18:16
@bdougherty I have updated this issue with test cases (CodePen)

**Comment by bdougherty** [comment] 2017-01-25 19:26
Looks like the same issue as #56. Domain-level privacy errors are rendered server-side when the player first loads, so the api isn't available and you won't get a message back.

**Closed by bdougherty** 2017-01-25 19:26 UTC
