### ISSUE TITLE
SyntaxError: Unexpected end of JSON input

### ISSUE THREAD

**Issue by Stefano1964** [vimeo/player.js#833] opened 2022-06-16 14:41 UTC
### Expected Behavior
No errors in console

### Actual Behavior
player.js:2 SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at E (player.js:2:6653)
    at player.js:2:20089
E @ player.js:2
(anonymous) @ player.js:2
postMessage (async)
canUsePostMessage @ ViewSDKInterface.js:1
(anonymous) @ ViewSDKInterface.js:1
(anonymous) @ ViewSDKInterface.js:1
YBdB @ ViewSDKInterface.js:1
__webpack_require__ @ ViewSDKInterface.js:1
(anonymous) @ ViewSDKInterface.js:1
URgk @ ViewSDKInterface.js:1
__webpack_require__ @ ViewSDKInterface.js:1
B/eG @ ViewSDKInterface.js:1
__webpack_require__ @ ViewSDKInterface.js:1
(anonymous) @ ViewSDKInterface.js:1
aE5D @ ViewSDKInterface.js:1
__webpack_require__ @ ViewSDKInterface.js:1
Vu6y @ ViewSDKInterface.js:1
__webpack_require__ @ ViewSDKInterface.js:1
window.adobe_dc_view_sdk.+Nns @ ViewSDKInterface.js:1
(anonymous) @ ViewSDKInterface.js:1

### Steps to Reproduce
the error show after the script is loaded, just loaded, i dont setup anything about vimeo player at this time
if then i setup the player with config, etc, the videos are showing without any problems and no error in console

in the past i never see this error

Chrome version 102.0.5005.115
player.js version v2.17.0 loaded from here https://player.vimeo.com/api/player.js

 anyway you have problem in your code if you dont check if json is valid...

**Comment by rkrishnan8594** [comment] 2022-06-16 17:23
Thanks for reporting this issue @Stefano1964 @tesar-tech. Could one of you share a CodePen or JSFiddle in which this issue is reproduced?

**Comment by agilemarcus** [comment] 2022-06-16 23:23
> Thanks for reporting this issue @Stefano1964 @tesar-tech. Could one of you share a CodePen or JSFiddle in which this issue is reproduced?

The problem is that you are trying to JSON.parse inside an event listener for `window.message` but that's a global event handler that receives every `postMessage` call, not just vimeo player specific calls.

The player logic needs to verify the origin and e.data element before attempting to parse it as JSON.  What happens is your library is trying to parse undefined when another library or the site itself uses postMessage for other purposes. 

You can reproduce the problem by calling `window.postMessage('test');` from the dev console in a page that has the player.js api loaded.

You can fix the problem by changing the if block in the second listener in the compiled player:
```
var t = E(e.data);
if (t && "ready" === t.event && c(e.origin))
```
to something like this:
```
var t = c(e.origin) && E(e.data ? e.data : "{}");
if (t && "ready" === t.event)
```
Which will first verify the origin, but also default e.data to an empty array in the event that you have other bugs upstream.

**Comment by Stefano1964** [comment] 2022-06-17 08:17
@agilemarcus so you are telling me that another library that i use is sending a post message? It's possible, i use a lot of library, but the problem come out recently. 
@rkrishnan8594 can you confirm?

**Comment by agilemarcus** [comment] 2022-06-17 15:27
> @agilemarcus so you are telling me that another library that i use is sending a post message? It's possible, i use a lot of library, but the problem come out recently. @rkrishnan8594 can you confirm?

@Stefano1964 yeah it's in your stack trace above...

```
...
(anonymous) @ player.js:2
postMessage (async)
canUsePostMessage @ ViewSDKInterface.js:1
(anonymous) @ ViewSDKInterface.js:1
...
```

Whatever ViewSDKInterface.js is (looks like an adobe lib) it's first checking for the ability to use postMessage, and then it's sending one out, which is then being intercepted by the vimeo player.  (I'm not sure why the `postMessage` line missing the @ source, but that's your culprit.)

I'm working on a patch for this today because we use a lot of postMessage calls in our app and this is filling up our logs with a tremendous amount of noise.  I'll post it here later as a temporary workaround until the player api is patched and pushed to production.

Until then, you could also just add this to your codebase:

```
console.warn = () => {};
```

...at the risk of losing some legitimate logging info if you rely on console.warn in your codebase.  The good news is that this isn't actually an error being thrown in your application as the player api catches the error and just warns about it in the console.

**Comment by rkrishnan8594** [comment] 2022-06-17 15:28
We're working on a fix for this error, but that's unlikely to be published until next week.

**Comment by Stefano1964** [comment] 2022-06-17 16:14
@agilemarcus this make sense, i use an adobe sdk library for displaying pdf doc (https://documentcloud.adobe.com/view-sdk/main.js), thanks a lot for the explanation
Ok @rkrishnan8594 we can wait, its' not blocking

**Closed** 2022-06-24 02:37 UTC
